# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-GoogleEarth-Document
version:      0.07
version_from: lib/Geo/GoogleEarth/Document.pm
installdirs:  site
requires:
    base:                          0
    strict:                        0
    Test::More:                    0
    XML::Simple:                   2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
